# This workflow builds and unit tests both main C++ API and also build/data tools for metadata generation.

name: Testing C++ API
on: pull_request
permissions:
  contents: read

jobs:
  cpp-test:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
    - name: Set up C++ environment
      run: |
        sudo apt-get update && \
        sudo apt-get install -y --fix-missing libboost-all-dev \
        cmake cmake-curses-gui libprotobuf-dev libgtest-dev libre2-dev \
        libicu-dev libboost-dev libboost-thread-dev libboost-system-dev \
        protobuf-compiler
      
    - name: Build C++
      run: |
        cd cpp
        mkdir build
        cd build
        cmake ..
        make
    
    - name: Test C++ Build Tools
      run: |
        ./cpp/build/tools/generate_geocoding_data_test
    
    - name: Test C++ API
      run: |
        ./cpp/build/libphonenumber_test
